version: "3.8"

services:
  backend: 
      build: 
        dockerfile: Dockerfile
        context: ./backend
        # Only build dev stage from Dockerfile
        target: development
      # Mount our host dir to the docker container
      # Mount backend dir (./backend) to (:) docker container (/keno/src/app)
      # Reflect File changes from host to container
      volumes:
        - ./backend:/keno/src/app
        - ./keno/src/app/node_modules
      # RUN in debug mode: npm run start:debug -> Also start your vscode debugger
      # RUN in dev mode: npm run start:dev
      command: npm run start:dev
      depends_on:
        - postgres
      environment:
        DATABASE_URL: postgres://user:password@postgres:5432/db
        NODE_ENV: development
        PORT: 5000
      ports:
        - 5000:5000
        - 9229:9229
  

  frontend: 
      build: 
        dockerfile: Dockerfile
        context: ./frontend
        target: development
      # Mount our host dir to the docker container
      # Mount backend dir (./backend) to (:) docker container (/keno/src/app)
      # Reflect File changes from host to container
      volumes:
         - ./frontend:/keno/frontend/src/app
         - ./keno/frontend/src/app/node_modules
      # RUN in debug mode: npm run start:debug -> Also start your vscode debugger
      # RUN in dev mode: npm run start:dev
      command: npm run dev
      environment:
          NODE_ENV: development
      ports:
         - 3000:3000
      links: 
         - backend


  postgres:
      image: postgres:14.4
      environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
      ports: 
        - 35000:5432
   

  postgres_admin:
      image: dpage/pgadmin4:4.28
      depends_on:
        - postgres
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: password
      ports: 
        - 5050:80
        
       

  